version: "3"
services:
  react-app:
    image: react-app
    build: ./front
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  api-server:
    image: api-server
    build: ./back
    environment:
      - PORT= 3001
    ports:
      - "3001:3001"
    networks:
      - mern-app
   
   proxy:
    image: nginx:alpine
    container_name: web-proxy
    restart: unless-stopped
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - services
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
